version: "3.9"

services:
  live:
    build: .
    command: /opt/intelie/live/bin/live console
    #volumes:
    depends_on:
      - db
      - db_history
    ports:
      - "8080:8080"

  db:
    image: mariadb:10.5
    #command: /usr/sbin/mysqld --disable-partition-engine-check
    #command: --disable-partition-engine-check
    #volumes:
    #  - ./data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=live
      - MARIADB_DATABASE=live
      - MARIADB_USER=live
      - MARIADB_PASSWORD=live

  db_history:
    image: postgres:latest
    #volumes:
    #  - ./psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=live
      - POSTGRES_USER=live
      - POSTGRES_PASSWORD=live

  jupyter:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
